import {
  SVGCentralBank,
  SVGFB,
  SVGIdea,
  SVGProfile2,
  SVGRel,
  SVGSlack,
  SVGStory2,
  SVGStory3,
  SVGStory4,
  SVGTesla,
  SVGIdea2,
  SVGJio,
  SVGTelia,
  SVGVoda,
  Airtel,
  Idea,
  Voda,
} from './Images';

export const todoList = [
  {
    id: '1',
    text: 'How are you bro ☺️?',
    isReply: false,
    name: 'Airtel',
    icon: Airtel,
    count: 0,
    read: true,
    isMute: true,
    isDelete: true,
    isPined: false,
  },
  {
    id: '2',
    text: 'Bye Bye ... ',
    isReply: false,
    name: 'Idea',
    icon: Idea,
    count: 2,
    read: false,
    isMute: false,
    isDelete: false,
    isPined: false,
  },
  {
    id: '3',
    text: 'How are you bro ☺️?',
    isReply: false,
    name: 'Airtel',
    icon: Airtel,
    count: 0,
    read: true,
    isMute: true,
    isDelete: true,
    isPined: false,
  },
  {
    id: '4',
    text: 'Bye Bye ... ',
    isReply: false,
    name: 'Idea',
    icon: Idea,
    count: 2,
    read: false,
    isMute: false,
    isDelete: false,
    isPined: false,
  },
  {
    id: '5',
    text: 'Lets meet today',
    isReply: false,
    name: 'Telia',
    icon: Voda,
    count: 0,
    read: true,
    isMute: false,
    isDelete: false,
    isPined: false,
  },
  {
    id: '6',
    text: 'Hello ☺️',
    isReply: true,
    name: 'Vodafone',
    icon: Voda,
    count: 5,
    read: false,
    isMute: true,
    isDelete: false,
    isPined: true,
  },
  {
    id: '7',
    text: 'Bye Bye ... ',
    isReply: false,
    name: 'Idea',
    icon: Idea,
    count: 2,
    read: false,
    isMute: false,
    isDelete: false,
    isPined: false,
  },
  {
    id: '8',
    text: 'Lets meet today',
    isReply: false,
    name: 'Telia',
    icon: Idea,
    count: 0,
    read: true,
    isMute: false,
    isDelete: false,
    isPined: false,
  },
  {
    id: '9',
    text: 'Lets fight 😡',
    isReply: true,
    name: 'Vodafone',
    icon: Voda,
    count: 5,
    read: false,
    isMute: true,
    isDelete: false,
    isPined: true,
  },
  {
    id: '10',
    text: 'Lets meet today',
    isReply: false,
    name: 'Telia',
    icon: Idea,
    count: 0,
    read: true,
    isMute: false,
    isDelete: false,
    isPined: false,
  },
  {
    id: '11',
    text: 'Gop Goa Gone ...',
    isReply: true,
    name: 'Vodafone',
    icon: Voda,
    count: 5,
    read: false,
    isMute: true,
    isDelete: false,
    isPined: true,
  },
  {
    id: '12',
    text: 'Lets meet today',
    isReply: false,
    name: 'Telia',
    icon: Voda,
    count: 0,
    read: true,
    isMute: false,
    isDelete: false,
    isPined: false,
  },
  // Add more items as needed
];
export const DISCOVER_CARD = [
  {
    id: '1',
    name: 'Central Bank',
    description: 'Bank And Finance',
    icon: SVGCentralBank,
    color: 'rgba(226, 0, 16, 1)',
  },
  {
    id: '2',
    name: 'Reliance',
    description: 'Telecommunication',
    icon: SVGRel,
    color: 'rgba(41, 85, 155, 1)',
  },
  {
    id: '3',
    name: 'Tesla',
    description: 'Telecommunication',
    icon: SVGTesla,
    color: 'rgba(0, 0, 0, 1)',
  },
  {
    id: '4',
    name: 'Facebook',
    description: 'Social Portal',
    icon: SVGFB,
    color: 'rgba(16, 145, 243, 1)',
  },
  {
    id: '5',
    name: 'Slack',
    description: 'Social Portral',
    icon: SVGSlack,
    color: 'rgba(236, 178, 46, 1)',
  },
  {
    id: '6',
    name: 'Idea',
    description: 'Telecommunication',
    icon: SVGIdea,
    color: 'rgba(0, 0, 0, 1)',
  },
  {
    id: '4',
    name: 'Facebook',
    description: 'Social Portal',
    icon: SVGFB,
    color: 'rgba(16, 145, 243, 1)',
  },
  {
    id: '5',
    name: 'Slack',
    description: 'Social Portral',
    icon: SVGSlack,
    color: 'rgba(236, 178, 46, 1)',
  },
  {
    id: '6',
    name: 'Idea',
    description: 'Telecommunication',
    icon: SVGIdea,
    color: 'rgba(0, 0, 0, 1)',
  },
];

export const STORIES = [
  {icon: SVGProfile2, name: 'Your Story'},
  {icon: SVGStory2, name: 'Dilshadkhan'},
  {icon: SVGStory3, name: 'iamblokee'},
  {icon: SVGStory4, name: 'Ambani'},
];

export const SEARCH_CARD = [
  {
    id: '1',
    text: 'How are you bro ☺️?',
    isReply: false,
    name: 'Airtel',
    icon: Airtel,
    count: 0,
    read: true,
    isMute: true,
    isDelete: true,
    isPined: false,
  },
  {
    id: '2',
    text: 'Bye Bye ... ',
    isReply: false,
    name: 'Idea',
    icon: SVGIdea2,
    count: 2,
    read: false,
    isMute: false,
    isDelete: false,
    isPined: false,
  },
  {
    id: '3',
    text: 'Lets meet today',
    isReply: false,
    name: 'Telia',
    icon: SVGTelia,
    count: 0,
    read: true,
    isMute: false,
    isDelete: false,
    isPined: false,
  },
  {
    id: '4',
    text: 'Hello ☺️',
    isReply: true,
    name: 'Vodafone',
    icon: SVGVoda,
    count: 5,
    read: false,
    isMute: true,
    isDelete: false,
    isPined: true,
  },
  {
    id: '8',
    text: 'Lets meet today',
    isReply: false,
    name: 'Telia',
    icon: SVGTelia,
    count: 0,
    read: true,
    isMute: false,
    isDelete: false,
    isPined: false,
  },
  {
    id: '9',
    text: 'Gop Goa Gone ...',
    isReply: true,
    name: 'Vodafone',
    icon: SVGVoda,
    count: 5,
    read: false,
    isMute: true,
    isDelete: false,
    isPined: true,
  },
  {
    id: '11',
    name: 'Central Bank',
    description: 'Bank And Finance',
    icon: SVGCentralBank,
    color: 'rgba(226, 0, 16, 1)',
  },
  {
    id: '12',
    name: 'Reliance',
    description: 'Telecommunication',
    icon: SVGRel,
    color: 'rgba(41, 85, 155, 1)',
  },
  {
    id: '13',
    name: 'Tesla',
    description: 'Telecommunication',
    icon: SVGTesla,
    color: 'rgba(0, 0, 0, 1)',
  },
  {
    id: '14',
    name: 'Facebook',
    description: 'Social Portal',
    icon: SVGFB,
    color: 'rgba(16, 145, 243, 1)',
  },
  {
    id: '15',
    name: 'Slack',
    description: 'Social Portral',
    icon: SVGSlack,
    color: 'rgba(236, 178, 46, 1)',
  },
  {
    id: '16',
    name: 'Idea',
    description: 'Telecommunication',
    icon: SVGIdea,
    color: 'rgba(0, 0, 0, 1)',
  },
];
// const todoList = [
//   {
//     id: '1',
//     text: 'How are you bro ☺️?',
//     isReply: false,
//     name: 'Airtel',
//     icon: Airtel,
//     count: 0,
//     read: true,
//     isMute: true,
//     isDelete: true,
//     isPined: false,
//   },
//   {
//     id: '2',
//     text: 'Bye Bye ... ',
//     isReply: false,
//     name: 'Idea',
//     icon: SVGIdea2,
//     count: 2,
//     read: false,
//     isMute: false,
//     isDelete: false,
//     isPined: false,
//   },
//   {
//     id: '1',
//     text: 'How are you bro ☺️?',
//     isReply: false,
//     name: 'Airtel',
//     icon: Airtel,
//     count: 0,
//     read: true,
//     isMute: true,
//     isDelete: true,
//     isPined: false,
//   },
//   {
//     id: '2',
//     text: 'Bye Bye ... ',
//     isReply: false,
//     name: 'Idea',
//     icon: SVGIdea2,
//     count: 2,
//     read: false,
//     isMute: false,
//     isDelete: false,
//     isPined: false,
//   },
//   {
//     id: '3',
//     text: 'Lets meet today',
//     isReply: false,
//     name: 'Telia',
//     icon: SVGTelia,
//     count: 0,
//     read: true,
//     isMute: false,
//     isDelete: false,
//     isPined: false,
//   },
//   {
//     id: '4',
//     text: 'Hello ☺️',
//     isReply: true,
//     name: 'Vodafone',
//     icon: SVGVoda,
//     count: 5,
//     read: false,
//     isMute: true,
//     isDelete: false,
//     isPined: true,
//   },
//   {
//     id: '5',
//     text: 'Bye Bye ... ',
//     isReply: false,
//     name: 'Idea',
//     icon: SVGIdea2,
//     count: 2,
//     read: false,
//     isMute: false,
//     isDelete: false,
//     isPined: false,
//   },
//   {
//     id: '6',
//     text: 'Lets meet today',
//     isReply: false,
//     name: 'Telia',
//     icon: SVGTelia,
//     count: 0,
//     read: true,
//     isMute: false,
//     isDelete: false,
//     isPined: false,
//   },
//   {
//     id: '7',
//     text: 'Lets fight 😡',
//     isReply: true,
//     name: 'Vodafone',
//     icon: SVGVoda,
//     count: 5,
//     read: false,
//     isMute: true,
//     isDelete: false,
//     isPined: true,
//   },
//   {
//     id: '8',
//     text: 'Lets meet today',
//     isReply: false,
//     name: 'Telia',
//     icon: SVGTelia,
//     count: 0,
//     read: true,
//     isMute: false,
//     isDelete: false,
//     isPined: false,
//   },
//   {
//     id: '9',
//     text: 'Gop Goa Gone ...',
//     isReply: true,
//     name: 'Vodafone',
//     icon: SVGVoda,
//     count: 5,
//     read: false,
//     isMute: true,
//     isDelete: false,
//     isPined: true,
//   },
//   {
//     id: '10',
//     text: 'Lets meet today',
//     isReply: false,
//     name: 'Telia',
//     icon: SVGTelia,
//     count: 0,
//     read: true,
//     isMute: false,
//     isDelete: false,
//     isPined: false,
//   },
//   {
//     id: '9',
//     text: 'Gop Goa Gone ...',
//     isReply: true,
//     name: 'Vodafone',
//     icon: SVGVoda,
//     count: 5,
//     read: false,
//     isMute: true,
//     isDelete: false,
//     isPined: true,
//   },
//   {
//     id: '10',
//     text: 'Lets meet today',
//     isReply: false,
//     name: 'Telia',
//     icon: SVGTelia,
//     count: 0,
//     read: true,
//     isMute: false,
//     isDelete: false,
//     isPined: false,
//   },
//   {
//     id: '9',
//     text: 'Gop Goa Gone ...',
//     isReply: true,
//     name: 'Vodafone',
//     icon: SVGVoda,
//     count: 5,
//     read: false,
//     isMute: true,
//     isDelete: false,
//     isPined: true,
//   },
//   {
//     id: '10',
//     text: 'Lets meet today',
//     isReply: false,
//     name: 'Telia',
//     icon: SVGTelia,
//     count: 0,
//     read: true,
//     isMute: false,
//     isDelete: false,
//     isPined: false,
//   },
//   {
//     id: '9',
//     text: 'Gop Goa Gone ...',
//     isReply: true,
//     name: 'Vodafone',
//     icon: SVGVoda,
//     count: 5,
//     read: false,
//     isMute: true,
//     isDelete: false,
//     isPined: true,
//   },
//   {
//     id: '10',
//     text: 'Lets meet today',
//     isReply: false,
//     name: 'Telia',
//     icon: SVGTelia,
//     count: 0,
//     read: true,
//     isMute: false,
//     isDelete: false,
//     isPined: false,
//   },
//   {
//     id: '9',
//     text: 'Gop Goa Gone ...',
//     isReply: true,
//     name: 'Vodafone',
//     icon: SVGVoda,
//     count: 5,
//     read: false,
//     isMute: true,
//     isDelete: false,
//     isPined: true,
//   },
//   {
//     id: '10',
//     text: 'Lets meet today',
//     isReply: false,
//     name: 'Telia',
//     icon: SVGTelia,
//     count: 0,
//     read: true,
//     isMute: false,
//     isDelete: false,
//     isPined: false,
//   },
//   // Add more items as needed
// ];
export const MENU_DATA_CHAT = [
  {
    name: 'View Contact',
  },
  {
    name: 'Search Messages',
  },
  {
    name: 'Mute Notifications',
  },
];
export const MENU_DATA_DISCOVER = [
  {
    name: 'View',
  },
  {
    name: 'Block',
  },
  {
    name: 'Favorite',
  },
];
